version: '3.8'
services:

  app:
    image: node:lts
    container_name: app
    restart: unless-stopped
    tty: true
    user: 1000:1000
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: yarn run start

networks:
  app-network:
    driver: bridge